version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=densys
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  api0:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "./main" ]
    environment:
      ENVIRONMENT: development
      AWS_BUCKET_NAME: "densys"
      AWS_REGION: "eu-central-1"
      AWS_ACCESS_KEY_ID: "AKIAUVYFMNWUJ5H5FJWL"
      AWS_SECRET_ACCESS_KEY: "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"
    depends_on:
      - postgres

networks:
  default:
    name: services-network
